
name: learn-github-actions
on:
  push: 
    branches:
        - 'main'
jobs:
  check-bats-version:
    if: ${{github.event.pull_request.merged == true}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hellow World"
  check-condition:
    needs: check-bats-version
    if: success()
    runs-on: ubuntu-latest
    steps:
      - run: echo "False"
