
name: Entropy CI/CD Pipeline
      
# on:
#   release:
#     types: [released]
#     branches:
#       - 'cloned/develop'

on:
  push:
    branches:
      - 'main'  
jobs:
  Deploy:
    runs-on: ubuntu-20.04
#     needs: Build
    steps:
      - name: Run ./Deploy.sh file   
        run: git remote set-url origin https://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@github.com
      - run: git fetch 
