
name: learn-github-actions
on: [push]
env:
  aws_region: ap-south-1
jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [v10.19.0]
        python-version: [v3.9]
        
    steps:
      - run: node --version
