
name: Entropy CI/CD Pipeline
      
on:
  push:
    branches:
      - 'main'
jobs:
  bash-example:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "Mona The Octocat"
    steps:
      - name: bash-version
        run: echo "::add-mask::${{MY_NAME}}"
