
name: learn-github-actions
on: [push]
env:
  aws_region: ap-south-1
jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [v10.19.0]
        python-version: [v3.9]
        
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: 'AKIASW36KQN24D5K6RH7'
          aws-secret-access-key: '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'
          aws-region: ${{env.aws_region}}
      - name: Login with ECR
        run: aws ecr get-login-password --region ${{env.aws_region}} | docker login --username AWS --password-stdin 186559136629.dkr.ecr.${{env.aws_region}}.amazonaws.com


          
