
name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    if: ${{true}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.action}}"
  check-condition:
    if: ${{false}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "False"
