
name: learn-github-actions
on: [push]
env:
  aws_region: ap-south-1
jobs:
  TEST:
    runs-on: ubuntu-20.04
    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
 
    - uses: actions/checkout@v2 
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        known_hosts: ${{ secrets.HOST_NAME }}
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts 
    - name: Running Deployment script..
      run: ssh ubuntu@${{ secrets.HOSTNAME }}
