name: learn-github-actions

on:
  release:
    types: [released]
#     branches:
#       - 'main'

# on:
#   push:
#     branches:
#        - 'CI-CD-TEst'
env:
  aws_region: ap-south-1
jobs:
  TEST:
    runs-on: ubuntu-20.04
    steps:
      - name: Take code from repository 📥
        uses: actions/checkout@v3
      - run: echo ${{github.ref}}
      - run: ls
