name: learn-github-actions
on:
  release:
    types: [released]
    branches:
      - 'main'
env:
  aws_region: ap-south-1
jobs:
  TEST:
    runs-on: ubuntu-20.04
    steps:
      - name: Take code from repository 📥
        uses: actions/checkout@v3
      - run: echo ${{github.ref_name}}
