
name: learn-github-actions
on:
  release:
    types: [released]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hellow World"
      - run: echo ${{job.status}}
  check-condition:
    needs: check-bats-version
    if: success()
    runs-on: ubuntu-latest
    steps:
      - run: echo "False"
