
name: learn-github-actions
on:
  pull_request_review:
    types:
      - submitted
jobs:
  check-bats-version:
    if: ${{true}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hellow World"
  check-condition:
    needs: check-bats-version
    if: ${{true}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "False"
